name: cypress-split-slack
on: [push]
jobs:
  split:
    uses: ./.github/workflows/reusable.yml
    with:
      n: 6
      browser: chrome
      marge: true
      slack: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }} 
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      SLACK_UID: ${{ secrets.SLACK_UID }} 




















